development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: The_Gram
  password: California11!

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: The_Gram
  password: California11!
